/**
 * Telegram Bot Integration
 * Sends notifications and daily reports to Telegram
 */

interface TelegramMessage {
  chat_id: string;
  text: string;
  parse_mode?: 'Markdown' | 'HTML';
}

export async function sendTelegramMessage(message: string): Promise<boolean> {
  const token = process.env.TELEGRAM_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID;

  if (!token || !chatId) {
    console.warn('[Telegram] Token or Chat ID not configured');
    return false;
  }

  try {
    const payload: TelegramMessage = {
      chat_id: chatId,
      text: message,
      parse_mode: 'Markdown',
    };

    const response = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      console.error('[Telegram] Failed to send message:', await response.text());
      return false;
    }

    return true;
  } catch (error) {
    console.error('[Telegram] Error sending message:', error);
    return false;
  }
}

export async function sendDailyReport(report: any): Promise<boolean> {
  const message = `
🧠 *Infinity Core Agent - Daily Report*
📅 Date: ${report.date}

*System Status:*
${Object.entries(report.status).map(([key, value]) => `• ${key}: ${value}`).join('\n')}

*Issues:* ${report.issues.length > 0 ? report.issues.join(', ') : 'None'}
*Uptime:* ${report.uptime}

_Generated by Infinity Core Agent_
  `.trim();

  return sendTelegramMessage(message);
}

export async function sendAlert(title: string, details: string): Promise<boolean> {
  const message = `
⚠️ *${title}*

${details}

_Infinity Core Agent Alert_
  `.trim();

  return sendTelegramMessage(message);
}

